-- Mood-based playlists generated by suggestion-engine
CREATE TABLE IF NOT EXISTS mood_playlists (
    id          SERIAL PRIMARY KEY,
    label       TEXT NOT NULL,
    cluster_id  INT UNIQUE,
    track_count INT DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mood_track_map (
    mood_playlist_id INT REFERENCES mood_playlists(id) ON DELETE CASCADE,
    video_id         TEXT REFERENCES yt_tracks(id) ON DELETE CASCADE,
    score            FLOAT,
    PRIMARY KEY (mood_playlist_id, video_id)
);

-- Precomputed top-N similarity index (populated by suggestion-engine)
CREATE TABLE IF NOT EXISTS track_similarity (
    video_id         TEXT REFERENCES yt_tracks(id) ON DELETE CASCADE,
    similar_video_id TEXT REFERENCES yt_tracks(id) ON DELETE CASCADE,
    score            FLOAT NOT NULL,
    PRIMARY KEY (video_id, similar_video_id)
);

CREATE INDEX IF NOT EXISTS idx_track_similarity_video_id ON track_similarity(video_id);
